# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'submenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class subMenu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setStyleSheet("background-color: rgb(170, 255, 127)")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 180, 171, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showProfileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showProfileButton.sizePolicy().hasHeightForWidth())
        self.showProfileButton.setSizePolicy(sizePolicy)
        self.showProfileButton.setStyleSheet("background-color:white\n")
        self.showProfileButton.setObjectName("showProfileButton")
        self.verticalLayout.addWidget(self.showProfileButton)
        self.editStudentButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.editStudentButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editStudentButton.sizePolicy().hasHeightForWidth())
        self.editStudentButton.setSizePolicy(sizePolicy)
        self.editStudentButton.setStyleSheet("background-color:white")
        self.editStudentButton.setObjectName("editStudentButton")
        self.verticalLayout.addWidget(self.editStudentButton)
        self.removeStudentButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeStudentButton.sizePolicy().hasHeightForWidth())
        self.removeStudentButton.setSizePolicy(sizePolicy)
        self.removeStudentButton.setStyleSheet("background-color:white")
        self.removeStudentButton.setObjectName("removeStudentButton")
        self.verticalLayout.addWidget(self.removeStudentButton)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: white")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 20, 131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/user.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sub Menu"))
        self.showProfileButton.setText(_translate("Form", "Show Profile"))
        self.editStudentButton.setText(_translate("Form", "Edit Student"))
        self.removeStudentButton.setText(_translate("Form", "Remove Student"))
        self.pushButton.setText(_translate("Form", "Exit to Menu "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
